# SPDX-FileCopyrightText: 2024 László Vaskó <vlaci@fastmail.com>
#
# SPDX-License-Identifier: EUPL-1.2

version = 1

[[annotations]]
path = "flake.lock"
SPDX-FileCopyrightText = "2024 László Vaskó <vlaci@fastmail.com>"
SPDX-License-Identifier = "EUPL-1.2"
